version: '3.9'

services:

  mongodb-product:
    image: mongo:latest # put the version which you want to use
    container_name: mongodb-product
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/product/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/product:/data/db
    command: mongod --auth


  mongo-express-product:
    image: mongo-express
    ports:
      - "8184:8184"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-product
    depends_on:
      - mongodb-product
    container_name: mongo-express-product
